name:  macOS Monterey 12

on:
  push:
    branches: [ master, support-c20 ]
  pull_request:
    branches: [ master, support-c20 ]
    
jobs:
  build:
    strategy:
      matrix:
        mode: [ Debug, Release ]
        cpp_version: [11, 20]
        
    runs-on: macos-12
    
    steps:
    - name: check out
      uses: actions/checkout@v3
      
    - name: configure cmake
      run:  CXX=clang++ CC=clang cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCPP_STANDARD=${{ matrix.cpp_version }}
      
    - name: build project
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.mode }}

