name: Windows Server 2022

on: 
  push:
    branches: [ master, support-c20 ]
  pull_request:
    branches: [ master, support-c20 ]
    
jobs:
  build:
    runs-on: windows-latest
    
    strategy: 
      matrix:
        mode: [Debug, Release]
        cpp_version: [11, 20]
        arch: [x64]
    
    env: 
      CXX: cl.exe
      CC: cl.exe
    
    steps:
      - name: check out
        uses: actions/checkout@v3
        
      - name: generate project
        run: cmake -B ${{ github.workspace }}\build -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -A${{ matrix.arch }} -DCPP_STANDARD=${{ matrix.cpp_version }}
        
      - name: build project
        run: cmake --build ${{ github.workspace }}\build --config ${{ matrix.mode }}
